services:
  jupyterlab:
    image: blnkoff/spark-jupyter:latest
    container_name: jupyterlab
    environment:
      - JUPYTER_TOKEN=hello_world
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./build/workspace:/opt/workspace
  spark-master:
    image: blnkoff/spark-master:latest
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - ./build/workspace:/opt/workspace
  spark-worker-1:
    image: blnkoff/spark-worker:latest
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8081:8081
    volumes:
      - ./build/workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: blnkoff/spark-worker:latest
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8082:8081
    volumes:
      - ./build/workspace:/opt/workspace
    depends_on:
      - spark-master

