jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/publish
        with:
          version: ${{ github.event.inputs.version }}
          variant: ${{ github.event.inputs.variant }}
